[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "khuzdul"
version = "0.1.0a1"
description = "A strict, zero-abstraction two-pass x86-64 assembler"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "mihinN"}
]

[project.optional-dependencies]
# Installed only when you run `pip install -e .[dev]`
dev = [
    "pytest>=7.0.0",
]

[project.scripts]
# This creates the terminal command 'khuzdul' 
# and points it to the main() function inside khuzdul.py
khuzdul = "khuzdul:main"

[tool.setuptools]
# Tells the build system to include these folders and your main script
packages = ["assembler", "isa"]
py-modules = ["khuzdul"]

[tool.pytest.ini_options]
# Automatically makes pytest output cleaner and points it to your test folder
addopts = "-v"
testpaths = ["test"]
